services:
    postgres:
        image: postgres:16
        container_name: ecommerce-db
        restart: always
        ports:
            - '${POSTGRES_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-nestjs}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - ecommerce-network

networks:
    ecommerce-network:
        driver: bridge

volumes:
    postgres-data:
