services:
    postgres:
        image: postgres:16
        container_name: ecommerce-db
        restart: always
        ports:
            - '${POSTGRES_PORT:-5432}:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-nestjs}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - ecommerce-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: ecommerce-pgadmin
        restart: always
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - ecommerce-network
        depends_on:
            - postgres

networks:
    ecommerce-network:
        driver: bridge

volumes:
    postgres-data:
    pgadmin-data:
